export enum DomainErrorCode {
    NO_ERROR,
    UNDOCUMENTED,
    INPUT_DATA_NOT_VALID,
    RESOURCE_NOT_FOUND,
    DATA_FROM_STORAGE_NOT_VALID,
    CARD_NOT_FOUND,
    USER_NOT_FOUND,
    SUBSCRIPTION_NOT_EXISTS,
    USER_IS_ALREADY_SUBSCRIBED_TO_CARD,
    CARD_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    REQUIRED_REQUEST_FIELD_IS_MISSING,
    PERSISTENCE_METHOD_NOT_DECLARED,
}


